name: cts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - ipython
  - matplotlib
  - pip
  - pip:
    - pytorch-lightning
    - scikit-learn
    - pandas_datareader
    - torchmetrics
    - imbalanced-learn
    - openpyxl